version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  node-exporter:
    container_name: knower-node-exporter
    image: prom/node-exporter
    ports:
      - '9100:9100'

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/varlib/grafana:/varlib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=knower_grafana_pass
    depends_on:
      - prometheus
    ports:
      - '3000:3000'