global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'
  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'
  - job_name: 'mysql'
    static_configs:
      - targets:
        - 'mysql-exporter:9104'
  - job_name: 'redis'
    static_configs:
      - targets:
        - 'redis-exporter:9121'
